server:
  port: 9090
  
spring:
  application:
    name: CUSTOMERORDERSERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/customerOrderdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mvc:
  view:
    prefix: /WEB-INF/jsps/
    suffix: .jsp