server:
  port: 9080
  
spring:
  application:
    name: RESULTSERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/questiondb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka