server:
  port: 9050
  
spring:
  application:
    name: REGISTERSERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/Moviedb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka